# file: vattukc/netlify.toml (Tại thư mục gốc)

[build]
  # Thư mục cơ sở: Đặt là client (nơi chứa file package.json của Frontend)
  base = "client"
  # Thư mục đầu ra: Tên dự án Next.js build
  publish = ".next"
  # Lệnh build: Chạy lệnh build chuẩn của Next.js
  command = "npm run build" 

[build.environment]
  # BUỘC SỬ DỤNG NODE.JS VÀ NPM PHIÊN BẢN ỔN ĐỊNH
  NODE_VERSION = "20.x"
  NPM_VERSION = "9.6.7"